{
 "title": "QEM DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SERVER SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Server",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_server_summary{status=~\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL SERVER SUCCESS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_server_summary{status=\"success\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL SERVER ERROR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_server_summary{status=~\"error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_servers_cpu_percentage",
     "legendFormat": "{{serverName}}"
    }
   ]
  },
  {
   "title": "Full Load Average Throughput in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_server_full_load_avg_throughput_bytes",
     "legendFormat": "{{serverName}}"
    }
   ]
  },
  {
   "title": "Memory Utilization Average Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_servers_memory_utilization_avg_percentage",
     "legendFormat": "{{serverName}}"
    }
   ]
  },
  {
   "title": "Attunity CPU Utilization Average Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_server_attunity_cpu_avg_percentage",
     "legendFormat": "{{serverName}}"
    }
   ]
  },
  {
   "title": "Machine CPU Utilization Average Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 24 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_server_machine_cpu_avg_percentage",
     "legendFormat": "{{serverName}}"
    }
   ]
  },
  {
   "title": "Total Disk in Server (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_servers_disk_utilization_bytes{metricType=\"total_disk\"}",
     "legendFormat": "{{serverName}}"
    }
   ]
  },
  {
   "title": "Used Disk in Server (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 32 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_servers_disk_utilization_bytes{metricType=\"used_disk\"}",
     "legendFormat": "{{serverName}}"
    }
   ]
  },
  {
   "title": "Total Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_servers_memory_utilization_bytes{metricType=\"total_memory\"}",
     "legendFormat": "{{serverName}}"
    }
   ]
  },
  {
   "title": "Used Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 40 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_servers_memory_utilization_bytes{metricType=\"used_memory\"}",
     "legendFormat": "{{serverName}}"
    }
   ]
  },
  { "title": "TASK SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "TASK TOTAL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_task_summary{status=~\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TASK RUNNING",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_task_summary{status=~\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TASK STOPPED",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_task_summary{status=~\"stopped\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TASK ERROR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_task_summary{status=~\"error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task average disk in percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_task_avg_disk_percentage",
     "legendFormat": "{{taskName}}"
    }
   ]
  },
  {
   "title": "Task average CPU in percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 55 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_task_avg_cpu_percentage",
     "legendFormat": "{{taskName}}"
    }
   ]
  },
  {
   "title": "Task average memory in bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_task_avg_memory_bytes",
     "legendFormat": "{{taskName}}"
    }
   ]
  },
  {
   "title": "Disk Utilization Average Percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 65 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_servers_disk_utilization_avg_percentage",
     "legendFormat": "{{serverName}}"
    }
   ]
  },
  {
   "title": "Task Average Source Throughput in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_task_avg_source_throughput_bytes",
     "legendFormat": "{{taskName}}"
    }
   ]
  },
  {
   "title": "Task Average Target Throughput in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 75 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_task_avg_target_throughput_bytes",
     "legendFormat": "{{taskName}}"
    }
   ]
  },
  {
   "title": "Task average source latency in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_task_avg_source_latency_seconds",
     "legendFormat": "{{taskName}}"
    }
   ]
  },
  {
   "title": "Task average apply latency in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 83 },
   "targets": [
    {
     "expr": "qlik_enterprise_manager_task_avg_target_apply_seconds",
     "legendFormat": "{{taskName}}"
    }
   ]
  }
 ]
}